apiVersion: v1
kind: ReplicationController
metadata:
  name: my-rc
  labels: 
    app: my-app
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-c
          image: httpd
          ports:
            - containerPort: 80
  selector:
    app: my-app
  
--- 
apiVersion: v1
kind: Service
metadata:
  name: my-svc
  labels:
    app: my-app
spec:
    ports:
      - port: 80
        targetPort: 80
        protocol: TCP
        name: http
    type: NodePort
    selector:
      app: my-app